/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.person;

/**
 *
 * @author ruchachotalia
 */
public class createPerson extends javax.swing.JPanel {

    /**
     * Creates new form createPerson
     */
    public createPerson() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personcityTxt = new javax.swing.JTextField();
        personnameLbl = new javax.swing.JLabel();
        personlocalityTxt = new javax.swing.JTextField();
        personageLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        personweightLbl = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        personaddressLbl = new javax.swing.JLabel();
        personcityLbl = new javax.swing.JLabel();
        personlocalityLbl = new javax.swing.JLabel();
        personnameTxt = new javax.swing.JTextField();
        personageTxt = new javax.swing.JTextField();
        personweightTxt = new javax.swing.JTextField();
        personaddressTxt = new javax.swing.JTextField();
        createpersonprofileLbl = new javax.swing.JLabel();
        createpersonheightLbl = new javax.swing.JLabel();
        createpatientheightTxt = new javax.swing.JTextField();
        hospitalLbl = new javax.swing.JLabel();
        hospitalTxt = new javax.swing.JTextField();

        personcityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personcityTxtActionPerformed(evt);
            }
        });

        personnameLbl.setText("Name");

        personageLbl.setText("Age");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        personweightLbl.setText("Weight");

        createBtn.setText("Create");

        personaddressLbl.setText("Address");

        personcityLbl.setText("City");

        personlocalityLbl.setText("Locality");

        personnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personnameTxtActionPerformed(evt);
            }
        });

        personweightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personweightTxtActionPerformed(evt);
            }
        });

        createpersonprofileLbl.setText("Create Person Profile");

        createpersonheightLbl.setText("Height");

        createpatientheightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createpatientheightTxtActionPerformed(evt);
            }
        });

        hospitalLbl.setText("Hospital");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createpersonheightLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createBtn))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(personnameLbl)
                                    .addComponent(personageLbl)
                                    .addComponent(personweightLbl)
                                    .addComponent(personaddressLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(personcityLbl)
                                    .addComponent(personlocalityLbl))
                                .addComponent(hospitalLbl))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hospitalTxt)
                                .addComponent(createpersonprofileLbl)
                                .addComponent(personlocalityTxt)
                                .addComponent(personcityTxt)
                                .addComponent(personaddressTxt)
                                .addComponent(personweightTxt)
                                .addComponent(personageTxt)
                                .addComponent(personnameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(createpatientheightTxt)))))
                .addContainerGap(314, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {createpatientheightTxt, personaddressTxt, personageTxt, personcityTxt, personlocalityTxt, personnameTxt, personweightTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(createpersonprofileLbl)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personnameLbl)
                    .addComponent(personnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personageLbl)
                    .addComponent(personageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personweightLbl)
                    .addComponent(personweightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createpersonheightLbl)
                    .addComponent(createpatientheightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personaddressLbl)
                    .addComponent(personaddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personcityLbl)
                    .addComponent(personcityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personlocalityLbl)
                    .addComponent(personlocalityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalLbl)
                    .addComponent(hospitalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(createBtn))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void personnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personnameTxtActionPerformed

    private void personweightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personweightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personweightTxtActionPerformed

    private void personcityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personcityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personcityTxtActionPerformed

    private void createpatientheightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createpatientheightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createpatientheightTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField createpatientheightTxt;
    private javax.swing.JLabel createpersonheightLbl;
    private javax.swing.JLabel createpersonprofileLbl;
    private javax.swing.JLabel hospitalLbl;
    private javax.swing.JTextField hospitalTxt;
    private javax.swing.JLabel personaddressLbl;
    private javax.swing.JTextField personaddressTxt;
    private javax.swing.JLabel personageLbl;
    private javax.swing.JTextField personageTxt;
    private javax.swing.JLabel personcityLbl;
    private javax.swing.JTextField personcityTxt;
    private javax.swing.JLabel personlocalityLbl;
    private javax.swing.JTextField personlocalityTxt;
    private javax.swing.JLabel personnameLbl;
    private javax.swing.JTextField personnameTxt;
    private javax.swing.JLabel personweightLbl;
    private javax.swing.JTextField personweightTxt;
    // End of variables declaration//GEN-END:variables
}
