/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.person;

import javax.swing.JPanel;
import model.person;

/**
 *
 * @author ruchachotalia
 */
public class viewUpdatePersonDetalis extends javax.swing.JPanel {

    /**
     * Creates new form viewUpdatePersonDetalis
     */
    
    private person person;
    private JPanel userProcessContainer;
    private Boolean isEdit = Boolean.FALSE;
    
    public viewUpdatePersonDetalis(JPanel userProcessContainer, person person, Boolean isEdit) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        persondetailsLbl = new javax.swing.JLabel();
        patientnameLbl = new javax.swing.JLabel();
        personupdateageLbl = new javax.swing.JLabel();
        patientnameTxt = new javax.swing.JTextField();
        personnameageTxt = new javax.swing.JTextField();
        backupdateBtn = new javax.swing.JButton();
        editupdateBtn = new javax.swing.JButton();
        saveupdateBtn = new javax.swing.JButton();
        personupdateweightLbl = new javax.swing.JLabel();
        personupdateheightLbl = new javax.swing.JLabel();
        personupdateweightTxt = new javax.swing.JTextField();
        personupdateheightTxt = new javax.swing.JTextField();

        persondetailsLbl.setText("Person Details");

        patientnameLbl.setText("Patient Name");

        personupdateageLbl.setText("Age");

        backupdateBtn.setText("<<Back");

        editupdateBtn.setText("Edit");
        editupdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editupdateBtnActionPerformed(evt);
            }
        });

        saveupdateBtn.setText("Save");

        personupdateweightLbl.setText("Weight");

        personupdateheightLbl.setText("Height");

        personupdateheightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personupdateheightTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(persondetailsLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personupdateheightLbl)
                            .addComponent(personupdateweightLbl))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personupdateweightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personupdateheightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(personupdateageLbl)
                                    .addComponent(backupdateBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(patientnameLbl)))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editupdateBtn)
                                .addGap(126, 126, 126)
                                .addComponent(saveupdateBtn))
                            .addComponent(personnameageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(108, 128, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {patientnameTxt, personnameageTxt, personupdateheightTxt, personupdateweightTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(persondetailsLbl)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientnameLbl)
                    .addComponent(patientnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personupdateageLbl)
                    .addComponent(personnameageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personupdateweightLbl)
                    .addComponent(personupdateweightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personupdateheightLbl)
                    .addComponent(personupdateheightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editupdateBtn)
                    .addComponent(backupdateBtn)
                    .addComponent(saveupdateBtn))
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editupdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editupdateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editupdateBtnActionPerformed

    private void personupdateheightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personupdateheightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personupdateheightTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backupdateBtn;
    private javax.swing.JButton editupdateBtn;
    private javax.swing.JLabel patientnameLbl;
    private javax.swing.JTextField patientnameTxt;
    private javax.swing.JLabel persondetailsLbl;
    private javax.swing.JTextField personnameageTxt;
    private javax.swing.JLabel personupdateageLbl;
    private javax.swing.JLabel personupdateheightLbl;
    private javax.swing.JTextField personupdateheightTxt;
    private javax.swing.JLabel personupdateweightLbl;
    private javax.swing.JTextField personupdateweightTxt;
    private javax.swing.JButton saveupdateBtn;
    // End of variables declaration//GEN-END:variables
}
