/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.util.Date;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Intergerverifier;
import model.Patient;
import model.person;
import model.vitalSign;

/**
 *
 * @author ruchachotalia
 */
public class createVitalsign extends javax.swing.JPanel {

    /**
     * Creates new form createVitalsign
     */
    
    private person person;
    
    private Patient patient;
    private JPanel userProcessContainer;
    
    public createVitalsign(JPanel upc, Patient patient) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.patient = patient;
    }
    
    private void addVerifiers() {
        InputVerifier integerVerifier = new Intergerverifier();
        o2Txt.setInputVerifier(integerVerifier);
        heartrateTxt.setInputVerifier(integerVerifier);
        systolicbpTxt.setInputVerifier(integerVerifier);
        weightTxt.setInputVerifier(integerVerifier);
        temperatureTxt.setInputVerifier(integerVerifier);
        commentTxt.setInputVerifier(integerVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entervitalsignLbl = new javax.swing.JLabel();
        o2Lbl = new javax.swing.JLabel();
        heartrateLbl = new javax.swing.JLabel();
        sysbpLbl = new javax.swing.JLabel();
        weightLbl = new javax.swing.JLabel();
        o2Txt = new javax.swing.JTextField();
        heartrateTxt = new javax.swing.JTextField();
        systolicbpTxt = new javax.swing.JTextField();
        weightTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        tempLbl = new javax.swing.JLabel();
        temperatureTxt = new javax.swing.JTextField();
        commentLbl = new javax.swing.JLabel();
        commentTxt = new javax.swing.JTextField();

        entervitalsignLbl.setText("Enter Vital Signs");

        o2Lbl.setText("O2 rate");

        heartrateLbl.setText("Heart Rate");

        sysbpLbl.setText("Systolic Blood Pressure");

        weightLbl.setText("Weight");

        backBtn.setText("<<Back");

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        tempLbl.setText("Temperature");

        commentLbl.setText("Any additional comments:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(entervitalsignLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(weightLbl)
                                .addComponent(sysbpLbl)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(o2Lbl)
                                    .addGap(131, 131, 131)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heartrateLbl)
                                    .addComponent(tempLbl)
                                    .addComponent(commentLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(o2Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(heartrateTxt)
                            .addComponent(systolicbpTxt)
                            .addComponent(weightTxt)
                            .addComponent(temperatureTxt)
                            .addComponent(commentTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createBtn)))
                .addGap(233, 233, 233))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(entervitalsignLbl)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(o2Lbl)
                    .addComponent(o2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heartrateLbl)
                    .addComponent(heartrateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sysbpLbl)
                    .addComponent(systolicbpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLbl)
                    .addComponent(weightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempLbl)
                    .addComponent(temperatureTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(commentLbl)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(commentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(createBtn))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        try {
            int respiratoryRate = Integer.parseInt(o2Txt.getText());
            int heartRate = Integer.parseInt(heartrateTxt.getText());
            int bloodPressure = Integer.parseInt(systolicbpTxt.getText());
            int weight = Integer.parseInt(weightTxt.getText());
            float temperature = Float.parseFloat(temperatureTxt.getText());
            String comment = commentTxt.getText();
            
            vitalSign VitalSign = patient.getVitalSignHistory().createAndAddVitalSign();
            VitalSign.setRespiratoryRate(respiratoryRate);
            VitalSign.setHeartRate(heartRate);
            VitalSign.setBloodPressure(bloodPressure);
            VitalSign.setTemperature((float) temperature);
            VitalSign.setWeight(weight);
            VitalSign.setComment(comment);
            
            /*Set current date and time as TimeStamp*/
            VitalSign.setTimestamp(new Date());
            JOptionPane.showMessageDialog(this, "Vital signs added!!", "Update",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please enter correct values",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel commentLbl;
    private javax.swing.JTextField commentTxt;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel entervitalsignLbl;
    private javax.swing.JLabel heartrateLbl;
    private javax.swing.JTextField heartrateTxt;
    private javax.swing.JLabel o2Lbl;
    private javax.swing.JTextField o2Txt;
    private javax.swing.JLabel sysbpLbl;
    private javax.swing.JTextField systolicbpTxt;
    private javax.swing.JLabel tempLbl;
    private javax.swing.JTextField temperatureTxt;
    private javax.swing.JLabel weightLbl;
    private javax.swing.JTextField weightTxt;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
