/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

/**
 *
 * @author ruchachotalia
 */
public class managePatient extends javax.swing.JPanel {

    /**
     * Creates new form managePatient
     */
    public managePatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managepatientsLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        managepatientcreateBtn = new javax.swing.JButton();
        managepatienteditBtn = new javax.swing.JButton();
        managepatientviewBtn = new javax.swing.JButton();
        managepatientdeleteBtn = new javax.swing.JButton();
        managepatientbackBtn = new javax.swing.JButton();
        managepatientrefreshBtn = new javax.swing.JButton();
        managepatientsearchTxt = new javax.swing.JTextField();
        managepatientsearchBtn = new javax.swing.JButton();

        managepatientsLbl.setText("Manage Patients");

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Age", "Locality"
            }
        ));
        jScrollPane1.setViewportView(patientTable);

        managepatientcreateBtn.setText("Create");

        managepatienteditBtn.setText("Edit");

        managepatientviewBtn.setText("View");

        managepatientdeleteBtn.setText("Delete");

        managepatientbackBtn.setText("<<Back");

        managepatientrefreshBtn.setText("Refresh");
        managepatientrefreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managepatientrefreshBtnActionPerformed(evt);
            }
        });

        managepatientsearchBtn.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(managepatientsLbl)
                .addGap(299, 299, 299))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(managepatientcreateBtn)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(managepatienteditBtn)
                    .addComponent(managepatientbackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managepatientsearchTxt))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managepatientsearchBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managepatientrefreshBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(managepatientviewBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(managepatientdeleteBtn)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(managepatientsLbl)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(managepatientcreateBtn)
                        .addComponent(managepatienteditBtn)
                        .addComponent(managepatientviewBtn))
                    .addComponent(managepatientdeleteBtn))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managepatientbackBtn)
                    .addComponent(managepatientrefreshBtn))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managepatientsearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managepatientsearchBtn))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managepatientrefreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managepatientrefreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managepatientrefreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton managepatientbackBtn;
    private javax.swing.JButton managepatientcreateBtn;
    private javax.swing.JButton managepatientdeleteBtn;
    private javax.swing.JButton managepatienteditBtn;
    private javax.swing.JButton managepatientrefreshBtn;
    private javax.swing.JLabel managepatientsLbl;
    private javax.swing.JButton managepatientsearchBtn;
    private javax.swing.JTextField managepatientsearchTxt;
    private javax.swing.JButton managepatientviewBtn;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables
}
