/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.personDirectory;

/**
 *
 * @author ruchachotalia
 */

public class patientmanagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form patientmanagerWorkArea
     */
    private JPanel userProcessContainer;
    private personDirectory personDirectory;
    public patientmanagerWorkArea(JPanel userProcessContainer,
            personDirectory personDirectory) {
        initComponents();
        this.personDirectory= personDirectory;
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientdirectoryBtn = new javax.swing.JButton();
        encounterhistoryBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        patientdirectoryBtn.setText("Patient Directory");
        patientdirectoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientdirectoryBtnActionPerformed(evt);
            }
        });

        encounterhistoryBtn.setText("Encounter History");
        encounterhistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterhistoryBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(encounterhistoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(patientdirectoryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(patientdirectoryBtn)
                .addGap(44, 44, 44)
                .addComponent(encounterhistoryBtn)
                .addGap(42, 42, 42)
                .addComponent(logoutBtn)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientdirectoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientdirectoryBtnActionPerformed
        // TODO add your handling code here:
        managePatient mpJPanel=  new managePatient (userProcessContainer, personDirectory);
        userProcessContainer.add("mpJPanel", mpJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_patientdirectoryBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void encounterhistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterhistoryBtnActionPerformed
        // TODO add your handling code here:
        manageVitalsign mvsJPanel= 
                new manageVitalsign (userProcessContainer, personDirectory);
        userProcessContainer.add("mvsJPanel", mvsJPanel);
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_encounterhistoryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encounterhistoryBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton patientdirectoryBtn;
    // End of variables declaration//GEN-END:variables
}
