/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Patient;

/**
 *
 * @author ruchachotalia
 */
public class viewUpdatePatientdetails extends javax.swing.JPanel {

    /**
     * Creates new form viewUpdatePatientdetails
     */
    private Patient Patient;
    private JPanel userProcessContainer;
    private Boolean isEdit = Boolean.FALSE;
    public viewUpdatePatientdetails(JPanel userProcessContainer, Patient patient, Boolean TRUE) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientidTxt = new javax.swing.JTextField();
        primarydocnameTxt = new javax.swing.JTextField();
        patientdetailsbackBtn = new javax.swing.JButton();
        patientdetailsaddpatientBtn = new javax.swing.JButton();
        patientdetailsLbl = new javax.swing.JLabel();
        patientidLbl = new javax.swing.JLabel();
        primarydocnameLbl = new javax.swing.JLabel();
        patientdetailseditBtn = new javax.swing.JButton();

        patientdetailsbackBtn.setText("<<Back");
        patientdetailsbackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientdetailsbackBtnActionPerformed(evt);
            }
        });

        patientdetailsaddpatientBtn.setText("Add Patient");
        patientdetailsaddpatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientdetailsaddpatientBtnActionPerformed(evt);
            }
        });

        patientdetailsLbl.setText("Patient Details");

        patientidLbl.setText("Patient ID");

        primarydocnameLbl.setText("Primary Doctor Name");

        patientdetailseditBtn.setText("Edit");
        patientdetailseditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientdetailseditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientidLbl)
                                    .addComponent(primarydocnameLbl))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(patientidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(primarydocnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(patientdetailsbackBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientdetailseditBtn)
                                .addGap(18, 18, 18)
                                .addComponent(patientdetailsaddpatientBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(patientdetailsLbl)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(patientdetailsLbl)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientidLbl)
                    .addComponent(patientidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primarydocnameLbl)
                    .addComponent(primarydocnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientdetailsbackBtn)
                    .addComponent(patientdetailsaddpatientBtn)
                    .addComponent(patientdetailseditBtn))
                .addContainerGap(206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientdetailsbackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientdetailsbackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_patientdetailsbackBtnActionPerformed

    private void modifyTextFields(Boolean isEdit) {
        if (isEdit) {
            patientidTxt.setEnabled(true);
            primarydocnameTxt.setEnabled(true);
            
        } else {
            patientidTxt.setEnabled(false);
            primarydocnameTxt.setEnabled(false);
            
    }
    }
     private Boolean checkBlankInput() {
        if (patientidTxt.getText().length()==0 || primarydocnameTxt.getText().length() == 0)
                {
            return false;
        } else {
            return true;
        }
    }
    private void patientdetailsaddpatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientdetailsaddpatientBtnActionPerformed
        // TODO add your handling code here:
         if (checkBlankInput()) {
            Patient.setPatientID(patientidTxt.getText());
            Patient.setPrimaryDoctorName(primarydocnameTxt.getText());
            
            JOptionPane.showMessageDialog(this, "Patient updated!!", "Update", 
                    JOptionPane.INFORMATION_MESSAGE);
            modifyTextFields(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct values", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_patientdetailsaddpatientBtnActionPerformed

    private void patientdetailseditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientdetailseditBtnActionPerformed
        // TODO add your handling code here:
        modifyTextFields(true);
    }//GEN-LAST:event_patientdetailseditBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel patientdetailsLbl;
    private javax.swing.JButton patientdetailsaddpatientBtn;
    private javax.swing.JButton patientdetailsbackBtn;
    private javax.swing.JButton patientdetailseditBtn;
    private javax.swing.JLabel patientidLbl;
    private javax.swing.JTextField patientidTxt;
    private javax.swing.JLabel primarydocnameLbl;
    private javax.swing.JTextField primarydocnameTxt;
    // End of variables declaration//GEN-END:variables
}
