/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author ruchachotalia
 */
public class doctor extends javax.swing.JPanel {

    /**
     * Creates new form doctor
     */
    public doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createdoctorrecordLbl = new javax.swing.JLabel();
        doctoridLbl = new javax.swing.JLabel();
        doctornameLbl = new javax.swing.JLabel();
        departmentLbl = new javax.swing.JLabel();
        docusernameLbl = new javax.swing.JLabel();
        docpasswordLbl = new javax.swing.JLabel();
        doctoridTxt = new javax.swing.JTextField();
        doctornameTxt = new javax.swing.JTextField();
        departmentTxt = new javax.swing.JTextField();
        docusernameTxt = new javax.swing.JTextField();
        docpasswordTxt = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();

        createdoctorrecordLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        createdoctorrecordLbl.setText("Create Doctor Record");

        doctoridLbl.setText("Doctor Id");

        doctornameLbl.setText("Doctor Name");

        departmentLbl.setText("Department");

        docusernameLbl.setText("Username");

        docpasswordLbl.setText("Password");

        createBtn.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctornameLbl)
                    .addComponent(departmentLbl)
                    .addComponent(docusernameLbl)
                    .addComponent(docpasswordLbl)
                    .addComponent(doctoridLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createdoctorrecordLbl)
                    .addComponent(docpasswordTxt)
                    .addComponent(docusernameTxt)
                    .addComponent(departmentTxt)
                    .addComponent(doctornameTxt)
                    .addComponent(doctoridTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {departmentTxt, docpasswordTxt, doctoridTxt, doctornameTxt, docusernameTxt});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {departmentLbl, docpasswordLbl, doctoridLbl, doctornameLbl, docusernameLbl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(createdoctorrecordLbl)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctoridLbl)
                            .addComponent(doctoridTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(doctornameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctornameLbl))
                        .addGap(36, 36, 36)
                        .addComponent(departmentLbl))
                    .addComponent(departmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docusernameLbl)
                    .addComponent(docusernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docpasswordLbl)
                    .addComponent(docpasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel createdoctorrecordLbl;
    private javax.swing.JLabel departmentLbl;
    private javax.swing.JTextField departmentTxt;
    private javax.swing.JLabel docpasswordLbl;
    private javax.swing.JTextField docpasswordTxt;
    private javax.swing.JLabel doctoridLbl;
    private javax.swing.JTextField doctoridTxt;
    private javax.swing.JLabel doctornameLbl;
    private javax.swing.JTextField doctornameTxt;
    private javax.swing.JLabel docusernameLbl;
    private javax.swing.JTextField docusernameTxt;
    // End of variables declaration//GEN-END:variables
}
